import type { Email, Perfil, Roteiro, Tarefa } from "../shared/types/domain";
import type { Configuracao } from "./dataRepository";
export declare function blankRoteiro(): Roteiro;
export declare function createTask(config: Configuracao, input: Pick<Tarefa, "nome" | "link" | "criacao">): Tarefa;
export declare function createProfile(config: Configuracao, nome: string, tarefas: string[]): Perfil;
export declare function createEmail(config: Configuracao, input: Pick<Email, "nome" | "titulo" | "corpo">): Email;
export declare function deactivateTaskBundle(config: Configuracao, taskId: string): Configuracao;
export declare function reactivateTaskBundle(config: Configuracao, taskId: string): Configuracao;
export declare function setProfileTaskAssociations(config: Configuracao, profileId: string, tarefas: string[]): Configuracao;
export declare function updateLayout(config: Configuracao, layout: Configuracao["layout"]): Configuracao;
